version: "3.8"

services:
  web:
    build:
      context: .
    ports:
      - "5173:5173"
      - "8000:8000"
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx json-server --watch database.json --port 8000 & npm test & npm run dev"
